blank_issues_enabled: false
contact_links:
  - name: VMware Cloud Foundation Product Documentation
    url: 'https://techdocs.broadcom.com/en/VMware/Cloud-Foundation/index.html
    about: Find more information in the official VMware Cloud Foundation documentation.''
